GamerRadar/Controllers/UserGamesController.cs
using GamerRadar.Models;
using GamerRadar.ViewModels.UserGames;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using System.Xml.Linq;

namespace GamerRadar.Controllers
{
    public class UserGamesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize]
        public ActionResult Search()
        {
            Session["Game"] = null;
            var gamesSelectListItem = GetGamesSelectList();
            var userGamesSearchViewModel = new UserGamesSearchViewModel(gamesSelectListItem, 0);
            return View(userGamesSearchViewModel);
        }

        [Authorize]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Search(UserGamesSearchViewModel userGamesSearchViewModel)
        {
            Session["Game"] = userGamesSearchViewModel;
            return RedirectToAction("Result");
        }

        private UserGamesViewModel CreateUserGamesViewModel(UserGamesSearchViewModel userGamesSearchViewModel)
        {
            if (userGamesSearchViewModel == null)
            {
                return null;
            }

            var userGames = new List<UserGame>();

            var userId = User.Identity.GetUserId();

            Game game = null;
            if (!string.IsNullOrEmpty(userGamesSearchViewModel.ScannedGameName))
            {
                userGames = db.UserGames.Where(ug => ug.Game.Name == userGamesSearchViewModel.ScannedGameName && ug.User.Id != userId).ToList();
                game = db.Games.FirstOrDefault(g => g.Name == userGamesSearchViewModel.ScannedGameName);
            }
            else if (userGamesSearchViewModel.SelectedGameId != 0)
            {
                userGames = db.UserGames.Where(ug => ug.Game.ID == userGamesSearchViewModel.SelectedGameId && ug.User.Id != userId).ToList();
                game = db.Games.FirstOrDefault(g => g.ID == userGamesSearchViewModel.SelectedGameId);
            }

            var userGameViewModels = new List<UserGameViewModel>(userGames.Select(ug => new UserGameViewModel(ug)));

            string address = db.Users.First(u => u.Id == userId).Location;

            Tuple<double, double> userLatitudeAndLongitude = GetLatitudeAndLongitudeOfUser(address);

            foreach (var userGameViewModel in userGameViewModels)
            {
                userGameViewModel.Distance =
                    GetLocationsOfUserAndStrangerAndCalculateDistanceBetweenThem(userLatitudeAndLongitude,
                        userGameViewModel.Location);
            }

            var userGamesViewModel = new UserGamesViewModel(userGameViewModels, game?.Name, game?.ID);
            return userGamesViewModel;
        }

        [Authorize]
        public ActionResult Result()
        {
            UserGamesSearchViewModel userGamesSearchViewModel = Session["Game"] as UserGamesSearchViewModel;
            var userGamesViewModel = CreateUserGamesViewModel(userGamesSearchViewModel);

            if (userGamesViewModel == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(userGamesViewModel);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private IEnumerable<SelectListItem> GetGamesSelectList()
        {
            var games = db.Games.Where(g => g.Valid && g.Approved).ToList();
            games.Add(new Game());
            games = games.OrderBy(p => p.Name).ToList();
            return new SelectList(games, "ID", "Name");
        }

        private static double CalculateDistanceUsingHaversine(double userLatitude, double strangerLatitude, double userLongitude, double strangerLongitude)
        {
            const double earthRadius = 6371;

            userLatitude = (Math.PI / 180) * userLatitude;
            strangerLatitude = (Math.PI / 180) * strangerLatitude;
            userLongitude = (Math.PI / 180) * userLongitude;
            strangerLongitude = (Math.PI / 180) * strangerLongitude;

            var x = Math.Sin((strangerLatitude - userLatitude) / 2);
            var y = Math.Sin((strangerLongitude - userLongitude) / 2);
            var z = x * x + Math.Cos(userLatitude) * Math.Cos(strangerLatitude) * y * y;

            var distance = 2 * earthRadius * Math.Asin(Math.Sqrt(z));

            return distance;
        }

        private Tuple<double, double> GetLatitudeAndLongitudeOfUser(string address)
        {
            string userRequestUri = string.Format("https://maps.googleapis.com/maps/api/geocode/xml?address={0}&key=AIzaSyAq8BJjhCh1zFmk5AvcHOdVb645HFgV5QE", address);

            WebRequest request = WebRequest.Create(userRequestUri);
            WebResponse response = request.GetResponse();
            XDocument xdoc = XDocument.Load(response.GetResponseStream());

            XElement result = xdoc.Element("GeocodeResponse").Element("result");
            XElement locationElement = result.Element("geometry").Element("location");
            XElement latitudeElement = locationElement.Element("lat");
            XElement longitudeElement = locationElement.Element("lng");

            var userLatitude = double.Parse(latitudeElement.Value, CultureInfo.InvariantCulture);
            var userLongitude = double.Parse(longitudeElement.Value, CultureInfo.InvariantCulture);

            Tuple<double, double> userLatitudeAndLongitude = new Tuple<double, double>(userLatitude, userLongitude);

            return userLatitudeAndLongitude;
        }

        private string GetLocationsOfUserAndStrangerAndCalculateDistanceBetweenThem(Tuple<double, double> userLatitudeAndLongitude, string strangerAddress)
        {
            string strangerRequestUri = string.Format("https://maps.googleapis.com/maps/api/geocode/xml?address={0}&key=AIzaSyAq8BJjhCh1zFmk5AvcHOdVb645HFgV5QE", strangerAddress);

            WebRequest request = WebRequest.Create(strangerRequestUri);
            WebResponse response = request.GetResponse();
            XDocument xdoc = XDocument.Load(response.GetResponseStream());


            XElement result = xdoc.Element("GeocodeResponse").Element("result");

            if (result == null)
            {
                return string.Format("N/A");
            }

            XElement locationElement = result.Element("geometry").Element("location");
            XElement latitudeElement = locationElement.Element("lat");
            XElement longitudeElement = locationElement.Element("lng");

            var strangerLatitude = double.Parse(latitudeElement.Value, CultureInfo.InvariantCulture);
            var strangerLongitude = double.Parse(longitudeElement.Value, CultureInfo.InvariantCulture);

            var distance = CalculateDistanceUsingHaversine(userLatitudeAndLongitude.Item1, strangerLatitude, userLatitudeAndLongitude.Item2, strangerLongitude);

            return distance.ToString("F");
        }
    }
}

GamerRadar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - GamerRadar</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href='@Url.Action("Index", "Home")'>
                <img src='@Url.Content("~/Images/logo.png")' style="width: 300px; padding-top: 8px"/>
            </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="capture-smallz">@Html.ActionLink("Games", "Index", "Games")</li>
                <li class="capture-smallz">@Html.ActionLink("Find friends", "Search", "UserGames")</li>
                <li class="capture-smallz">@Html.ActionLink("About", "About", "Home")</li>
                <li class="capture-smallz">@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr />
    <footer>
        <p class="capture-smallz">&copy; @DateTime.Now.Year - GamerRadar</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

GamerRadar/Views/Shared/_QRCodeLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - GamerRadar</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="padding-top: 20px;">
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>